### ISSUE TITLE
Wacom Intuos PT S not recognized by plug

### ISSUE THREAD

**Issue by stsdc** [elementary/switchboard-plug-wacom#13]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Installed this plug on elementary os 5.1.4, but it doesn't recognize my Wacom Intuos PT S Pen.

### To Reproduce
Open the plug.

### Expected behavior
Probably should display some settings, key mappings or at least info about connected tablet. Also shows no stylus detected.

### Screenshots or screen recordings

![obraz](https://user-images.githubusercontent.com/6031763/82742387-befd1d80-9d5d-11ea-88c9-aeb7701213e6.png)

![obraz](https://user-images.githubusercontent.com/6031763/82742409-fcfa4180-9d5d-11ea-8c4f-6e097bb1348d.png)

## Platform Information
![obraz](https://user-images.githubusercontent.com/6031763/82742389-d1775700-9d5d-11ea-9403-147743b3b056.png)

- [x] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by peteruithoven** [comment]
I'm afraid those tablet settings are all the implemented settings at the moment: 
https://github.com/elementary/switchboard-plug-wacom/blob/master/src/Views/TabletView.vala

You mention that the stylus isn't detected, how do the Wacom settings communicate this? 

The fact  that the stylus isn't detected is probably because this relatively new wacom isn't supported yet, which has little to do with the Wacom Settings. 
This is an interesting source: https://linuxwacom.github.io/

If the stylus does work (only the settings don't show), it's probably a manner of adding the appropriate data file, see: https://github.com/linuxwacom/libwacom/wiki/Troubleshooting
They have lot's of existing more up to date data files at:
https://github.com/linuxwacom/libwacom/tree/master/data
I'd recommend searching the repo on your model's name. 

Overall this seems like a out of scope and/or unclear issue. An issue on the ability input key mapping seems more appropriate, which exists: https://github.com/elementary/switchboard-plug-wacom/issues/1

**Comment by stsdc** [comment]
@peteruithoven It is supported, because I'm using it almost a 5 years now.

What did I expect with this plug? Show at least info from `xsetwacom --list devices` or `lsusb` so I'll know that device is connected. 
I did expect that this minimum of settings implemented in the plug will work.

**Comment by stsdc** [comment]
This issue is basically #3. Apologies for duplicate.

**Comment by peteruithoven** [comment]
> @peteruithoven It is supported, because I'm using it almost a 5 years now.

To clarify and I agree this is a bit confusing, there is a difference between the wacom functioning and their settings being updatable. 

> Show at least info from `xsetwacom --list devices` or `lsusb` so I'll know that device is connected.

I don't understand how you can use `xsetwacom` and I can't find or install it. Are you also on Hera?
(I've already posted it as a [question on Stack Exchange](https://elementaryos.stackexchange.com/questions/25301/xsetwacom-on-elementary-os-hera))

**Comment by stsdc** [comment]
> Are you also on Hera?

![obraz](https://user-images.githubusercontent.com/6031763/88328359-9a56ff00-cd28-11ea-834a-01cff556da15.png)

**Comment by peteruithoven** [comment]
One tip further and xsetwacom works for me, as do the Stylus settings. 

If the wacom works, but you don't get the stylus settings I'd recommend checking the troubleshooting:
> If the stylus does work (only the settings don't show), it's probably a manner of adding the appropriate data file, see: https://github.com/linuxwacom/libwacom/wiki/Troubleshooting
> They have lot's of existing more up to date data files at:
> https://github.com/linuxwacom/libwacom/tree/master/data
> I'd recommend searching the repo on your model's name.

**Comment by stsdc** [comment]
The .data file is present. 
![obraz](https://user-images.githubusercontent.com/6031763/88416785-144abf00-cde1-11ea-9c1c-65e448e79bd1.png)
